/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TopUpRouteImport } from './routes/top-up'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomAdvisorsIndexRouteImport } from './routes/custom-advisors.index'
import { Route as CustomAdvisorsNewRouteImport } from './routes/custom-advisors.new'
import { Route as CustomAdvisorsAdvisorIdRouteImport } from './routes/custom-advisors.$advisorId'
import { Route as ChatChatIdRouteImport } from './routes/chat.$chatId'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TopUpRoute = TopUpRouteImport.update({
  id: '/top-up',
  path: '/top-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomAdvisorsIndexRoute = CustomAdvisorsIndexRouteImport.update({
  id: '/custom-advisors/',
  path: '/custom-advisors/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomAdvisorsNewRoute = CustomAdvisorsNewRouteImport.update({
  id: '/custom-advisors/new',
  path: '/custom-advisors/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomAdvisorsAdvisorIdRoute = CustomAdvisorsAdvisorIdRouteImport.update({
  id: '/custom-advisors/$advisorId',
  path: '/custom-advisors/$advisorId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/top-up': typeof TopUpRoute
  '/transactions': typeof TransactionsRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/custom-advisors/$advisorId': typeof CustomAdvisorsAdvisorIdRoute
  '/custom-advisors/new': typeof CustomAdvisorsNewRoute
  '/custom-advisors': typeof CustomAdvisorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/top-up': typeof TopUpRoute
  '/transactions': typeof TransactionsRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/custom-advisors/$advisorId': typeof CustomAdvisorsAdvisorIdRoute
  '/custom-advisors/new': typeof CustomAdvisorsNewRoute
  '/custom-advisors': typeof CustomAdvisorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/top-up': typeof TopUpRoute
  '/transactions': typeof TransactionsRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/custom-advisors/$advisorId': typeof CustomAdvisorsAdvisorIdRoute
  '/custom-advisors/new': typeof CustomAdvisorsNewRoute
  '/custom-advisors/': typeof CustomAdvisorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rewards'
    | '/settings'
    | '/top-up'
    | '/transactions'
    | '/chat/$chatId'
    | '/custom-advisors/$advisorId'
    | '/custom-advisors/new'
    | '/custom-advisors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rewards'
    | '/settings'
    | '/top-up'
    | '/transactions'
    | '/chat/$chatId'
    | '/custom-advisors/$advisorId'
    | '/custom-advisors/new'
    | '/custom-advisors'
  id:
    | '__root__'
    | '/'
    | '/rewards'
    | '/settings'
    | '/top-up'
    | '/transactions'
    | '/chat/$chatId'
    | '/custom-advisors/$advisorId'
    | '/custom-advisors/new'
    | '/custom-advisors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RewardsRoute: typeof RewardsRoute
  SettingsRoute: typeof SettingsRoute
  TopUpRoute: typeof TopUpRoute
  TransactionsRoute: typeof TransactionsRoute
  ChatChatIdRoute: typeof ChatChatIdRoute
  CustomAdvisorsAdvisorIdRoute: typeof CustomAdvisorsAdvisorIdRoute
  CustomAdvisorsNewRoute: typeof CustomAdvisorsNewRoute
  CustomAdvisorsIndexRoute: typeof CustomAdvisorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-up': {
      id: '/top-up'
      path: '/top-up'
      fullPath: '/top-up'
      preLoaderRoute: typeof TopUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-advisors/': {
      id: '/custom-advisors/'
      path: '/custom-advisors'
      fullPath: '/custom-advisors'
      preLoaderRoute: typeof CustomAdvisorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-advisors/new': {
      id: '/custom-advisors/new'
      path: '/custom-advisors/new'
      fullPath: '/custom-advisors/new'
      preLoaderRoute: typeof CustomAdvisorsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-advisors/$advisorId': {
      id: '/custom-advisors/$advisorId'
      path: '/custom-advisors/$advisorId'
      fullPath: '/custom-advisors/$advisorId'
      preLoaderRoute: typeof CustomAdvisorsAdvisorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RewardsRoute: RewardsRoute,
  SettingsRoute: SettingsRoute,
  TopUpRoute: TopUpRoute,
  TransactionsRoute: TransactionsRoute,
  ChatChatIdRoute: ChatChatIdRoute,
  CustomAdvisorsAdvisorIdRoute: CustomAdvisorsAdvisorIdRoute,
  CustomAdvisorsNewRoute: CustomAdvisorsNewRoute,
  CustomAdvisorsIndexRoute: CustomAdvisorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
